#! /usr/bin/env python
#
# Support module generated by PAGE version 4.6
# In conjunction with Tcl version 8.6
#    Mar 06, 2016 10:02:21 PM


import sys
import DASH

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global combobox
    combobox = StringVar()


def conCOM(p1):
    print('DASH_support.conCOM')
    sys.stdout.flush()


def portScan(p1):
    print('DASH_support.portScan')
    sys.stdout.flush()


def rght(p1):
    print('DASH_support.rght')
    sys.stdout.flush()


def rvrs(p1):
    print('DASH_support.rvrs')
    sys.stdout.flush()


def fwd(p1):
    print('DASH_support.fwd')
    sys.stdout.flush()


def lft(p1):
    print('DASH_support.lft')
    sys.stdout.flush()


def stop(p1):
    print('DASH_support.stop')
    sys.stdout.flush()


def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def goDASH(p1):
    print(p1.txtCommand.get())
    p1.listBox.tag_configure('color', foreground='#00aa00')
    p1.listBox.insert(END, ">" + p1.txtCommand.get(), 'color')
    p1.listBox.tag_configure('color1', foreground='#aa0000')
    p1.listBox.insert(END, " Power: " + str(p1.dutyCycle.get()) +  "\n", 'color1')
    p1.btnFwd.focus_set()
    sys.stdout.flush()


if __name__ == '__main__':
    import DASH
    DASH.vp_start_gui()
