#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.6
# In conjunction with Tcl version 8.6
#    Mar 06, 2016 10:02:16 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import DASH_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('DASH_GUI_v1')
    geom = "725x321+252+216"
    root.geometry(geom)
    DASH_support.set_Tk_var()
    w = DASH_GUI_v1 (root)
    DASH_support.init(root, w)
    root.mainloop()

w = None
def create_DASH_GUI_v1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('DASH_GUI_v1')
    geom = "725x321+252+216"
    w.geometry(geom)
    DASH_support.set_Tk_var()
    w_win = DASH_GUI_v1 (w)
    DASH_support.init(w, w_win, param)
    return w_win

def destroy_DASH_GUI_v1():
    global w
    w.destroy()
    w = None



class DASH_GUI_v1:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")

        self.goBtn = Button(master)
        self.goBtn.place(relx=0.39, rely=0.78, height=24, width=47)
        self.goBtn.configure(activebackground="#d9d9d9")
        self.goBtn.configure(activeforeground="#000000")
        self.goBtn.configure(background=_bgcolor)
        self.goBtn.configure(disabledforeground="#a3a3a3")
        self.goBtn.configure(foreground="#000000")
        self.goBtn.configure(highlightbackground="#d9d9d9")
        self.goBtn.configure(highlightcolor="black")
        self.goBtn.configure(pady="0")
        self.goBtn.configure(text='''Go''')

        self.Message1 = Message(master)
        self.Message1.place(relx=0.62, rely=0.12, relheight=0.07, relwidth=0.05)
        self.Message1.configure(background=_bgcolor)
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Port''')
        self.Message1.configure(width=60)

        self.comSelect = ttk.Combobox(master)
        self.comSelect.place(relx=0.68, rely=0.12, relheight=0.07, relwidth=0.2)
        self.comSelect.configure(textvariable=DASH_support.combobox)
        self.comSelect.configure(takefocus="")

        self.txtCommand = Entry(master)
        self.txtCommand.place(relx=0.04, rely=0.78, relheight=0.06
                , relwidth=0.34)
        self.txtCommand.configure(background="white")
        self.txtCommand.configure(disabledforeground="#a3a3a3")
        self.txtCommand.configure(font="TkFixedFont")
        self.txtCommand.configure(foreground="#000000")
        self.txtCommand.configure(highlightbackground="#d9d9d9")
        self.txtCommand.configure(highlightcolor="black")
        self.txtCommand.configure(insertbackground="black")
        self.txtCommand.configure(selectbackground="#c4c4c4")
        self.txtCommand.configure(selectforeground="black")
        self.txtCommand.bind('<Return>', lambda e: DASH_support.goDASH(self))

        self.btnFwd = Button(master)
        self.btnFwd.place(relx=0.74, rely=0.59, height=44, width=54)
        self.btnFwd.configure(activebackground="#d9d9d9")
        self.btnFwd.configure(activeforeground="#000000")
        self.btnFwd.configure(background=_bgcolor)
        self.btnFwd.configure(command=lambda:DASH_support.fwd(1))
        self.btnFwd.configure(disabledforeground="#a3a3a3")
        self.btnFwd.configure(foreground="#000000")
        self.btnFwd.configure(highlightbackground="#9b9b9b")
        self.btnFwd.configure(highlightcolor="#000000")
        self.btnFwd.configure(pady="0")
        self.btnFwd.configure(takefocus="0")
        self.btnFwd.configure(text='''Forward''')

        self.btnLeft = Button(master)
        self.btnLeft.place(relx=0.66, rely=0.75, height=44, width=54)
        self.btnLeft.configure(activebackground="#d9d9d9")
        self.btnLeft.configure(activeforeground="#000000")
        self.btnLeft.configure(background=_bgcolor)
        self.btnLeft.configure(command=lambda:DASH_support.lft(1))
        self.btnLeft.configure(disabledforeground="#a3a3a3")
        self.btnLeft.configure(foreground="#000000")
        self.btnLeft.configure(highlightbackground="#d9d9d9")
        self.btnLeft.configure(highlightcolor="black")
        self.btnLeft.configure(pady="0")
        self.btnLeft.configure(takefocus="0")
        self.btnLeft.configure(text='''Left''')

        self.btnRvs = Button(master)
        self.btnRvs.place(relx=0.74, rely=0.75, height=44, width=54)
        self.btnRvs.configure(activebackground="#d9d9d9")
        self.btnRvs.configure(activeforeground="#000000")
        self.btnRvs.configure(background=_bgcolor)
        self.btnRvs.configure(command=lambda:DASH_support.rvrs(1))
        self.btnRvs.configure(disabledforeground="#a3a3a3")
        self.btnRvs.configure(foreground="#000000")
        self.btnRvs.configure(highlightbackground="#d9d9d9")
        self.btnRvs.configure(highlightcolor="black")
        self.btnRvs.configure(pady="0")
        self.btnRvs.configure(takefocus="0")
        self.btnRvs.configure(text='''Reverse''')

        self.btnRight = Button(master)
        self.btnRight.place(relx=0.83, rely=0.75, height=44, width=54)
        self.btnRight.configure(activebackground="#d9d9d9")
        self.btnRight.configure(activeforeground="#000000")
        self.btnRight.configure(background=_bgcolor)
        self.btnRight.configure(command=lambda:DASH_support.rght(1))
        self.btnRight.configure(disabledforeground="#a3a3a3")
        self.btnRight.configure(foreground="#000000")
        self.btnRight.configure(highlightbackground="#d9d9d9")
        self.btnRight.configure(highlightcolor="black")
        self.btnRight.configure(pady="0")
        self.btnRight.configure(takefocus="0")
        self.btnRight.configure(text='''Right''')

        self.listBox = Text(master)
        self.listBox.place(relx=0.04, rely=0.03, relheight=0.7, relwidth=0.34)
        self.listBox.configure(background="white")
        self.listBox.configure(font="TkTextFont")
        self.listBox.configure(foreground="black")
        self.listBox.configure(highlightbackground="#d9d9d9")
        self.listBox.configure(highlightcolor="black")
        self.listBox.configure(insertbackground="black")
        self.listBox.configure(selectbackground="#c4c4c4")
        self.listBox.configure(selectforeground="black")
        self.listBox.configure(takefocus="0")
        self.listBox.configure(width=244)
        self.listBox.configure(wrap=WORD)

        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.goBtn.configure(command=lambda: DASH_support.goDASH(self))
        self.btnFwd.focus_set()
        self.btnFwd.bind('<Key-Up>',lambda e:DASH_support.fwd(1))
        self.btnFwd.bind('<KeyRelease-Up>',lambda e:DASH_support.stop(1))
        self.btnFwd.bind('<Key-Left>',lambda e:DASH_support.lft(1))
        self.btnFwd.bind('<KeyRelease-Left>',lambda e:DASH_support.stop(1))
        self.btnFwd.bind('<Key-Down>',lambda e:DASH_support.rvrs(1))
        self.btnFwd.bind('<KeyRelease-Down>',lambda e:DASH_support.stop(1))
        self.btnFwd.bind('<Key-Right>',lambda e:DASH_support.rght(1))
        self.btnFwd.bind('<KeyRelease-Right>',lambda e:DASH_support.stop(1))






if __name__ == '__main__':
    vp_start_gui()



